name: CI selenium

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.100'  

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
        
      - name: Start Web Application
        run: |
          nohup dotnet run --project P10ShopWebAPPMVC.Client/P10ShopWebAPPMVC.Client.csproj --launch-profile https > webapp.log 2>&1 &
          echo "Web application started successfully."

      - name: Start API
        run: | 
          nohup dotnet run --project P05Shop.API/P05Shop.API.csproj  > webapp.log 2>&1 &
          echo "API application started successfully."

      - name: Wait for Application to Start
        run: sleep 10s
        
      - name: Run Tests
        run: |        
          
          
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          
          dotnet test --no-restore --verbosity normal
         
        env:
          ASPNETCORE_ENVIRONMENT: "Development"
          CHROME_BIN: "/usr/bin/chromium-browser"
