name: Selenium

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: "P05Shop.API/appsettings.json"
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Run API
        run: nohup dotnet run --project P05Shop.API/P05Shop.API.csproj > API.log &
      - name: Run Web App
        run: nohup dotnet run --urls http://0.0.0.0:7255 --project P10ShopWebAPPMVC.Client/P10ShopWebAPPMVC.Client.csproj > App.log &
      - name: Wait
        run: sleep 10s
      - name: Set permissions
        run: chmod -R 777 .       

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Run tests
        id: tests
        run: dotnet test > TestOutput.log
        continue-on-error: true

      - name: Show test output
        uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: TestOutput.log
      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text }}

      - uses: actions/upload-artifact@v3
        if: steps.tests.outcome != 'success'
        with:
          name: Log
          path: TestOutput.log


      - name: Run tests and capture output
        run: |
          failed_tests_desc=$(grep -A 6 'Error Message:' TestOutput.log || true)
          echo "FailedTestsDesc=${failed_tests_desc}" >> $GITHUB_ENV

      - name: Use the captured output in another step
        run: |
          echo "Failed tests description: $FailedTestsDesc"
         

      - name: Send bug to Azure DevOps
        if: steps.tests.outcome != 'success'
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://dev.azure.com/01158651/mwoProjekt/_apis/wit/workitems/$task?api-version=7.1-preview.3"
          method: "POST"
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_TOKEN }}
          customHeaders: '{"Content-Type": "application/json-patch+json"}'
          data: |
              [
                {
                  "op": "add",
                  "path": "/fields/System.Title",
                  "value": "failed_tests"
                },
                {
                  "op": "add",
                  "path": "/fields/System.Description",
                  "value": "$failed_tests_desc"
                }
              ]
