name: Selenium

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'P05Shop.API/appsettings.json'
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Run API
      run: nohup dotnet run --project P05Shop.API/P05Shop.API.csproj > API.log &
    - name: Run Web App
      run: nohup dotnet run --project P10ShopWebAPPMVC.Client/P10ShopWebAPPMVC.Client.csproj --launch-profile https > App.log &
    - name: Wait
      run: sleep 10s
    - name: Set permissions
      run: chmod -R 777 .
    - name: Execute unit tests
      id: tests
      run: dotnet test > TestOutput.log
      continue-on-error: true 
    - uses: actions/upload-artifact@v3
      if: steps.tests.outcome != 'success'
      with:
        name: Log
        path: TestOutput.log
    - name: Notify
      if: steps.tests.outcome != 'success'
      uses: fjogeleit/http-request-action@v1
      with:
        url:  'https://dev.azure.com/01158651/mwoProjekt/_apis/wit/workitems/$Bug?api-version=7.1'
        method: 'POST'
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_TOKEN }}
        customHeaders: '{"Content-Type": "application/json-patch+json"}'
        data: '[ {"op": "add", "path": "/fields/System.Title", "from": null, "value": "Pipeline error: ${{ github.event.pull_request.title }}" }, { "op": "add", "path": "/fields/System.Description", "from": null, "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }]'
